// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcybohvhquvkeapisede.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjeWJvaHZocXV2a2VhcGlzZWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDA0MDMsImV4cCI6MjA2MDY3NjQwM30.1JguXCxZK4n-O4kRN3co3qOHgnAX6FUFNsngYG2rasI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);